### Data Fetching through API

In [1]:
import pandas as pd
import requests

In [ ]:
url = "https://ai-movie-recommender.p.rapidapi.com/api/trending" 

headers = {
	"x-rapidapi-key": "Your API Key",
    "x-rapidapi-host": "ai-movie-recommender.p.rapidapi.com",
}
response = requests.get(url, headers=headers)
data = response.json()['results']
# print(data)
# print(type(data)) #always check the type of data you get from API, since it is dictionary you need to convert it into dataframe, 

# if it directly returns list then use below code
# df = pd.DataFrame(data)

# else
df = pd.DataFrame(data)

In [3]:
new_df = df[['id','title','overview','popularity','release_date','vote_average','vote_count']]

In [4]:
# df[df['original_language'] ==   'en']
new_df.head() #now this is the dataframe of only one page, you can loop through all the pages and get the data of all the movies. Total there is 500 pages, you can use for loop to get the data of all the pages and then concatenate all the dataframes to get the final dataframe of all the movies.

,id,title,overview,popularity,release_date,vote_average,vote_count
0,1301421,The Sheep Detectives,George Hardy is a shepherd who reads detective...,109.3275,2026-04-30,7.520,221
1,1081003,Supergirl,When an unexpected and ruthless adversary stri...,144.8921,2026-06-23,5.900,60
2,1020047,In the Hand of Dante,A Vatican priest discovers Dante's original Di...,27.4576,2026-06-12,3.300,6
3,1084244,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,331.3196,2026-06-17,7.400,282
4,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",519.0790,2026-05-13,7.901,967

In [5]:
final_data = pd.DataFrame() #empty dataframe to store the data of all the pages

In [6]:
all_pages = [] #list to store the data of all the pages
for page in range(1, 4):# took only 3 pages to avoid hitting the API limit.
    response = requests.get(url, headers=headers, params={'page': page})
    df = pd.DataFrame(response.json()['results'])[['id','title','overview','popularity','release_date','vote_average','vote_count']]
    all_pages.append(df)
final_data = pd.concat(all_pages, ignore_index=True)

In [7]:
final_data.head()

,id,title,overview,popularity,release_date,vote_average,vote_count
0,1301421,The Sheep Detectives,George Hardy is a shepherd who reads detective...,109.3275,2026-04-30,7.520,221
1,1081003,Supergirl,When an unexpected and ruthless adversary stri...,144.8921,2026-06-23,5.900,60
2,1020047,In the Hand of Dante,A Vatican priest discovers Dante's original Di...,27.4576,2026-06-12,3.300,6
3,1084244,Toy Story 5,When Bonnie receives a Lilypad tablet as a gif...,331.3196,2026-06-17,7.400,282
4,1339713,Obsession,"After breaking the mysterious ""One Wish Willow...",519.0790,2026-05-13,7.901,967

In [8]:
# convert the final dataframe to csv file
final_data.to_csv('Trending_movies_data.csv')